development:
  adapter: sqlite3
  encoding: utf8
  database: db/development.sqlite3
  host: localhost
  pool: 5
  timeout: 5000


test:
  adapter: sqlite3
  encoding: utf8
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: ecommerce_production
  pool: 5
  timeout: 5000
  user: myapp
  password: Leehieeu666